### ISSUE TITLE
Slow to parse

### ISSUE THREAD

**Issue by calebcbaker** [stevenvachon/winattr#2]
Getting properties of a single file/folder can take 1/2 second, if looping over multiple files this can really add up.

**Comment by stevenvachon** [comment]
What version of Node?

**Comment by calebcbaker** [comment]
Node: 6.3.1
Electron: 1.6.2
OS: Win7 and Win10

**Comment by stevenvachon** [comment]
If it's taking a half second per file, then it must be using the command line fallback. I haven't tested this with Electron, but that could be causing the binding to fail.

**Comment by stevenvachon** [comment]
Ah, [it will be fixed when Node 8.x is released](https://github.com/xxoo/node-fswin/issues/15#issuecomment-272710630).

**Comment by calebcbaker** [comment]
Yeah after some digging around I found the fallback, and can verify that is being used. I thinking my next steps are to just use fswin directly but rebuild it to work with electron.

**Comment by stevenvachon** [comment]
Sounds like a lot of work for something that still currently works, albeit slow, and will be fixed for you within a couple of weeks.
