### ISSUE TITLE
Does not change attributes of folders

### ISSUE THREAD

**Issue by Bogdan-Kalynovskyi** [stevenvachon/winattr#3]
The tool changes attributes of files, but not folders. However, folders also have attributes that should be changed. 

Tested on latest WIn 10

**Comment by stevenvachon** [comment]
The [tests](https://github.com/stevenvachon/winattr/blob/master/test/test.js#L296) say otherwise. What version of Node.js and can you create a failing test?

**Comment by Bogdan-Kalynovskyi** [comment]
I'm using node 8.10.0 on windows 10. I've tested again and discovered that attributes are set on top-level folder, but not subfolders. So the tool recursively sets attributes on files but not folders.

**Comment by stevenvachon** [comment]
I think that's how Windows' file system works. You'll have to automate recursive changes yourself.
