### ISSUE TITLE
Node 10 is not supported

### ISSUE THREAD

**Issue by anmiles** [stevenvachon/winattr#6]
Hi!
I'm using Node 10 under Windows 10 64 bit.
Latest version of winattr depends on old version of fswin that doesn't include proper files for node 10.x.x (9.x.x is latest there). 
That's why whichLib always fallbacks to "shell" mode. In this mode setting attributes takes ~100 times more time that in "bindings" mode.
I manually changed version of fswin dependency to the latest fswin and re-installed fswin. After that winattr succeeded to work in "bindings" mode.

Could you please release winattr with newer version of winfs dependency?
Thank you! 
Anatoliy.

**Comment by diegobentes** [comment]
Hi!
same problem.

**Comment by stevenvachon** [comment]
Fixed in v3.0
